using System;
using System.Collections.Generic;
using System.Text;

namespace Deucarian.Editor
{
    /// <summary>Source formatting only; each domain selects its authoritative definitions and key type.</summary>
    public static class DeucarianKeySourceText
    {
        public const string Header = "// <auto-generated> Deucarian typed definition keys. Edit the source definitions, not this file. </auto-generated>";

        public static string Create(DeucarianAssetKeySource source)
        {
            var text = new StringBuilder(Header + "\nnamespace Deucarian.Generated\n{\n");
            text.Append("    [global::").Append(source.DefinitionSetAttribute.FullName).Append("]\n");
            text.Append("    public static class ").Append(Identifier(source.GeneratedClassName)).Append("\n    {\n");
            var names = new HashSet<string>(StringComparer.Ordinal);
            names.Add(Identifier(source.GeneratedClassName));
            foreach (var definition in source.ReadDefinitions())
            {
                string symbol = Identifier(definition.Label);
                if (!names.Add(symbol)) throw new InvalidOperationException("Two " + source.KeyType.Name + " definitions generate the same code name '" + symbol + "'. Give their source definitions different display names.");
                text.Append("        public static global::").Append(source.KeyType.FullName).Append(' ').Append(symbol)
                    .Append(" => new Definition(\"").Append(Escape(definition.Id)).Append("\");\n");
            }
            text.Append("        private sealed class Definition : global::").Append(source.KeyType.FullName)
                .Append("\n        {\n            public Definition(string id) : base(id) { }\n        }\n    }\n}\n");
            return text.ToString();
        }

        public static string Identifier(string label)
        {
            if (string.IsNullOrWhiteSpace(label)) throw new ArgumentException("A definition needs a display name to generate its code symbol.", nameof(label));
            var result = new StringBuilder();
            bool upper = true;
            foreach (char c in label)
            {
                if (!char.IsLetterOrDigit(c) && c != '_') { upper = true; continue; }
                if (result.Length == 0 && char.IsDigit(c)) result.Append('_');
                result.Append(upper ? char.ToUpperInvariant(c) : c);
                upper = false;
            }
            if (result.Length == 0) throw new ArgumentException("The definition display name must contain letters or digits.", nameof(label));
            string symbol = result.ToString();
            if (symbol == "Definition") symbol = "DefinitionKey";
            return symbol;
        }

        private static string Escape(string value) => value.Replace("\\", "\\\\").Replace("\"", "\\\"")
            .Replace("\r", "\\r").Replace("\n", "\\n").Replace("\t", "\\t").Replace("\0", "\\0");
    }
}
